[package]
name = "gql_print"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql_client = "0.9.0"
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
